// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'collectionmenuitem-fetch'
  | 'menuitem-fetch'
  | 'menutoolsitem-fetchall'
  | 'popwin-doimissing'
  | 'popwin-fetching'
  | 'popwin-fetchsuccess'
  | 'popwin-pdfnotavaliable'
  | 'popwin-unknownerror'
  | 'popwin-unknownerrorclick'
  | 'pref-about-title'
  | 'pref-about-version'
  | 'pref-autoDownload'
  | 'pref-github'
  | 'pref-title'
  | 'prefs-title';
